// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
void rcpp_hello_world();
RcppExport SEXP _duktape_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_hello_world();
    return R_NilValue;
END_RCPP
}
// rcpp_eval
void rcpp_eval(std::string script);
RcppExport SEXP _duktape_rcpp_eval(SEXP scriptSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type script(scriptSEXP);
    rcpp_eval(script);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_duktape_rcpp_hello_world", (DL_FUNC) &_duktape_rcpp_hello_world, 0},
    {"_duktape_rcpp_eval", (DL_FUNC) &_duktape_rcpp_eval, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_duktape(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
