# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    invisible(.Call(`_duktape_rcpp_hello_world`))
}

rcpp_eval <- function(script) {
    invisible(.Call(`_duktape_rcpp_eval`, script))
}

